import { Request, Response, NextFunction } from "express";
import { validationResult }from "express-validator/check";
import NewMember from "../model/NewMember";
import MembersDAO from '../model/MembersDAO';
import JWTokenHandler from './../../lib/Auth/JWTokenHandler'


export let get_members = (req: Request, res: Response, next: NextFunction) => {

    MembersDAO.getMembers().then((result) => {
        res.status(200).json({
            message: 'POST request to /members',
            createdMember: result
        });
    }).
    catch( error => {
        next( error );
    })

}

export let create_member = (req :Request, res: Response, next: NextFunction) => {

    //Get validation results generated by the middleware
    const errors = validationResult(req);
    
    //Check if there are any errors and return them as an array
    if ( ! errors.isEmpty() ) {
         return res.status(422).json({ errors: errors.array() });
    }

   
    let newmember = new NewMember(
        req.body.firstname,
        req.body.lastname,
        req.body.email,
        req.body.phone,
        req.body.gender,
        req.body.pin,
        req.body.rank
    )
   
    MembersDAO.addNewMember(newmember).then((result) => {
        res.status(201).json({
            message: 'POST request to /members',
            createdMember: result
        });
    }).
    catch( error => {
        next( error );
    })
    
}

export let login_member = (req: Request, res: Response, next: NextFunction) => {

    //extract user name and password from request

    //Check if credentials match
    MembersDAO.loginMember('john','john')
    .then((result) => {
        return JWTokenHandler.signToken(result)
    })
    .then((result) =>{
        res.status(201).json({
            token: result
        });
    })
    .catch( error => {
        next( error );
    })

}
