import { Request, Response, NextFunction } from "express";
import { validationResult }from "express-validator/check";
import MemberRegistrationInfo from "../model/MemberRegistrationInfo";
import MembersDAO from './../model/MembersDAO';


export let get_members = (req: Request, res: Response, next: NextFunction) => {
        res.status(200).json({
            message: 'GET request to /members'
        })  

}

export let create_member = (req :Request, res: Response, next: NextFunction) => {

    //Get validation results generated by the middleware
    const errors = validationResult(req);
    
    //Check if there are any errors and return them as an array
    if ( ! errors.isEmpty() ) {
         return res.status(422).json({ errors: errors.array() });
    }

   
    let newmember = new MemberRegistrationInfo(
        req.body.firstname,
        req.body.lastname,
        req.body.email,
        req.body.phone,
        req.body.gender,
        req.body.username,
        req.body.password,
        req.body.pin,
        req.body.rank
    )
   
    MembersDAO.addNewMember(newmember).then((result) => {
        res.status(201).json({
            message: 'POST request to /members',
            createdMember: result
        });
    }).
    catch( error => {
        next( error );
    })
    
}
